stages:
  - build
  - deploy
  - package
  - display

variables:
  PROJECT_NAME: test
  REGISTRY_URL: registry.cn-qingdao.aliyuncs.com/tayueliuxiang

build_test_docker:
  stage: build
  before_script:
#    - git submodule sync --recursive
#    - git submodule update --init --recursive
  script:
    - docker build . -t $PROJECT_NAME
    - docker tag $PROJECT_NAME $REGISTRY_URL/$PROJECT_NAME:hyperf1
    - docker push $REGISTRY_URL/$PROJECT_NAME:hyperf1
  only:
    - test
  tags:
    - builder

deploy_test_docker:
  stage: deploy
  script:
    - docker stack deploy -c deploy.test.yml --with-registry-auth $PROJECT_NAME
  only:
    - test
  tags:
    - deploy

build_docker:
  stage: package
  before_script:
#    - git submodule sync --recursive
#    - git submodule update --init --recursive
  script:
    - docker build . -t $PROJECT_NAME
    - docker tag $PROJECT_NAME $REGISTRY_URL/$PROJECT_NAME:test
    - docker tag $PROJECT_NAME $REGISTRY_URL/$PROJECT_NAME:latest
    - docker push $REGISTRY_URL/$PROJECT_NAME:test
    - docker push $REGISTRY_URL/$PROJECT_NAME:latest
  only:
    - test
  tags:
    - builder1

deploy_docker:
  stage: display
  script:
    - echo SUCCESS
  only:
    - test
  tags:
    - builder1
