version: '3.7'
services:
  test:
    image: $REGISTRY_URL/$PROJECT_NAME:hyperf1
    environment:
      - "APP_PROJECT=test"
      - "APP_ENV=test"
    ports:
      - 9501:9501
    deploy:
      replicas: 6
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      update_config:
        parallelism: 6
        delay: 5s
        order: start-first
    networks:
      - network
    configs:
      - source: hyperf_v1.0
        target: /opt/www/.env
configs:
  hyperf_v1.0:
    external: true
networks:
  network:
    external: true
